import Head from 'next/head'
import styled from 'styled-components'
import { Header } from '@/ui/layout/Header/Header'
import { Footer } from '@/ui/layout/Footer/Footer'
import { ModalsProvider, modals, useModals } from '@/features/modal'
import { Dialog } from '@/features/modal/layout/Dialog'
import { ModalEnum } from '@/features/modal/modal.type'

const PageWrapper = styled.div`
  position: relative;
  width: 100vw;
  min-width: var(--width-ipad);
  height: 100vh;
  background: transparent;
  &:before {
    z-index: -5;
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    /* z-index: -1; */
    background: linear-gradient(
      110deg, rgba(23,150,198,1) -30%,
      rgba(8,0,255,1) 10%,
      rgba(204,26,11,1) 70%,
      rgba(232,255,0,0.9752275910364145) 130%);
      opacity: 0.8;
  }
`

const Content = styled.main`
  z-index: 10;
  padding: calc(var(--header-height) + 16px) 16px 16px;
  display: grid;
  grid-template-columns: repeat(20, 48px);
  grid-template-rows: repeat(20, 48px);
  gap: 8px
`
const Desktop = () => {
  const { openModal } = useModals()

  const onClick = () => {
    openModal(
      ModalEnum.WINDOW, {
      width: 450,
    })
  }
  const onClick2 = () => {
    openModal(
      ModalEnum.FINDER, {
      width: 150,
      top: 100,
      left: 1000,
    })
  }

  return(
    <Content>
      <button onClick={onClick}>click</button>
      <button onClick={onClick2}>click</button>
  </Content>
  )
}

export default function Home() {

  return (
    <ModalsProvider initialModals={modals}>
      <Head>
        <title>MacOS Desktop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Header />
        <Desktop />
        <Footer />
      </PageWrapper>
    </ModalsProvider>
  )
}
